import { Inter } from "next/font/google";
import type { Metadata } from "next";


import { cn } from "@/lib/utils"; 
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/context/authContext";
import { NavigationBar } from "@/components/navbar";
import { ThemeProvider } from "@/context/themeProvider";
import { PersistLoginProvider } from "@/context/persistLoginContext";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative flex min-h-screen flex-col pt-[56px]">
            <main className="flex flex-col items-center">
              <AuthProvider>
                <PersistLoginProvider>
                  {children}
                </PersistLoginProvider>
              </AuthProvider>
            </main>
          </div>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
