import "./globals.css";
import { AuthProvider } from "@/context/authContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import { PersistLoginProvider } from "@/context/persistLoginContext";
import { ThemeProvider } from "@/context/themeProvider";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative flex min-h-screen flex-col pt-[56px]">
            <main className="flex h-screen flex-col items-center">
              <AuthProvider>
                <PersistLoginProvider>
                  <Navbar />
                  {children}
                </PersistLoginProvider>
              </AuthProvider>
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
